language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"

matrix:
    allow_failures:
        - python: "pypy"

before_script:
    - curl -s https://raw.github.com/pypa/virtualenv/master/virtualenv.py | python - -q vendor
    - vendor/bin/pip -q install -r requirements.txt
    - vendor/bin/python setup.py -q install

script:
    - app/console hello Fabien

notifications:
    email: false
