language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"

script:
    - app/console hello Fabien
    - contrib/build-standalone
    - contrib/build/console hello Fabien
 

notifications:
    email: false
