language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"

before_script:
    - python setup.py -q install

script:
    - app/console hello Fabien

notifications:
    email: false
